name = "nexo-inmueble"
main = "worker.js"
compatibility_date = "2026-08-19"

[placement]
mode = "smart"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "nexo-db"
database_id = "03a0f232-751a-4d5b-a865-473062fbefbe"

[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "nexo-index"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "BUCKET_IMAGENES"
bucket_name = "nexo-media"

[vars]
WHATSAPP_PHONE = "+5350000000"
